[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.11.1"
glob-match = "0.2.1"
ptrie = "0.7.2"
trie-rs = "0.4.2"
yada = "0.5.1"
# zipora = { version = "2.1.0", features = ["nightly"] }
